# This is a basic workflow to help you get started with Actions
name: CI

on:
  push:
    branches: [ master, EmileDerain-patch-1-GitHub-Action ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up JDK 1.17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17

      - name: Maven build
        run: mvn clean package

#      - name: Run Mutation Testing
#        run: mvn package -Ppitest org.pitest:pitest-maven:mutationCoverage


      - name: Discord Commits Message
        uses: Sniddl/discord-commits@v1.3
        with:
          webhook: "https://discord.com/api/webhooks/958486282735071312/hEz4ZkcN6b6f-uKruZJAS2Y3m8foboLoBxLI5DSVA_ViWiVtZvTpCn6Uo50SwBpl-mIe"
          message: "Successful commit"
          embed: '{ "title": "{{ commit.title }}", "description": "{{ commit.description }}", "url": "{{ commit.url }}", "author": { "name": "{{ commit.author.name }} ({{ commit.author.username }})", "icon_url": "https://avatars.io/gravatar/{{ commit.author.email }}"} }'

