# This is a basic workflow to help you get started with Actions
name: CI

on:
  push:
    branches: [ master, EmileDerain-patch-1-GitHub-Action ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    needs: [ Mutation ]
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up JDK 1.17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17

      - name: Maven build
        run: mvn clean package


  mutation:
#    if: ${{ always() && needs.build.result == 'success' }}
#    needs: [ Build ]
    name: Mutation
    runs-on: ubuntu-latest

    steps:
#      - name: Dossier
#        run: mvn -f qgl-21-22-mugiwara_cook/player/pom.xml
      - name: Run Mutation Testing
        run: mvn -f qgl-21-22-mugiwara_cook/player/pom.xml -Ppitest org.pitest:pitest-maven:mutationCoverage

  discordPerform:
    if: ${{ always() && needs.build.result == 'success' }}
    needs: [ Build ]
    name: Discord message
    runs-on: ubuntu-latest

    steps:
      - name: Discord Commits Message
        uses: Sniddl/discord-commits@v1.3
        with:
          webhook: "https://discord.com/api/webhooks/958658739844554792/6iX1_fez9_jJ7ctiOTY3NKiGeFSdB-dL1sBhWdW8Mrk-_y1R6W9Sfj_8tPpFVhViPbcG"
          message: "Successful build"  #: {{ github.event.head_commit.message }}
#          embed: '{ "title": "{{ commit.title }}", "description": "{{ commit.description }}", "url": "{{ commit.url }}", "author": { "name": "{{ commit.author.name }} ({{ commit.author.username }})", "icon_url": "https://avatars.io/gravatar/{{ commit.author.email }}"} }'


  discordFail:
    if: ${{ always() && needs.build.result == 'failure' }}
    needs: [ Build ]
    name: Discord message
    runs-on: ubuntu-latest

    steps:
      - name: Discord Commits Message
        uses: Sniddl/discord-commits@v1.3
        with:
          webhook: "https://discord.com/api/webhooks/958658739844554792/6iX1_fez9_jJ7ctiOTY3NKiGeFSdB-dL1sBhWdW8Mrk-_y1R6W9Sfj_8tPpFVhViPbcG"
          message: "Fail build"
#          embed: '{ "title": "{{ commit.title }}", "description": "{{ commit.description }}", "url": "{{ commit.url }}", "author": { "name": "{{ commit.author.name }} ({{ commit.author.username }})", "icon_url": "https://avatars.io/gravatar/{{ commit.author.email }}"} }'


